#! /bin/bash

usage()
{
    printf 'usage: %s [-n]\n' "$progname"
}

progname="$(basename $0)"
n=false
if [[ $# == 1 ]]
then
    if [[ "$1" == '-n' ]]
    then
        n=true
    else
        usage
    fi
fi

version=$(sed -Ene '/version:/ {s/: */=/; s/^[ \t]*//p;}' < openapi.yaml)

if [[ "$n" == true ]]
then
    echo "$version" | sed -Ee 's/version=//'
else
    echo "$version"
fi
