/**
* CulebraTester
* ## Snaky Android Test --- If you want to be able to try out the API using the **Execute** or **TRY** button from this page - an android device should be connected using `adb` - the server should have been started using `./culebratester2 start-server`  then you will be able to invoke the API and see the responses. 
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 *  * @param status  * @param statusCode  * @param errorMessage */
data class StatusResponse(
    val status: Status, val statusCode: Int? = null, val errorMessage: String? = null
) {
    /**
    * 
    * Values: oK,eRROR,uNKNOWKN
    */
    enum class Status(val value: String) {
        oK("OK"),
        eRROR("ERROR"),
        uNKNOWKN("UNKNOWN");
    }

    enum class StatusCode(val value: Int) {
        TIMEOUT(1000),
        TIMEOUT_WINDOW_UPDATE(1001),

        ARGUMENT(3000),
        ARGUMENT_MISSING(3001),

        INTERACTION(5000),
        INTERACTION_KEY(5001);
    }
}
