/**
 * CulebraTester
 * ## Snaky Android Test --- If you want to be able to try out the API using the **Execute** or **TRY** button from this page - an android device should be connected using `adb` - the server should have been started using `./culebratester2 start-server`  then you will be able to invoke the API and see the responses.
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.server.models


/**
 *  * @param status  * @param statusCode  * @param errorMessage */
data class StatusResponse(
    val status: Status, val statusCode: Int? = null, val errorMessage: String? = null
) {
    /**
     *
     * Values: oK,eRROR,uNKNOWKN
     */
    enum class Status(val value: String) {
        OK("OK"),
        ERROR("ERROR"),
        UNKNOWKN("UNKNOWN");
    }

    enum class StatusCode(val value: Int) {
        TIMEOUT_WINDOW_UPDATE(1001) {
            override fun message(): String {
                TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
            }
        },

        ARGUMENT_MISSING(3001) {

            override fun message(): String {
                TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
            }
        },

        INTERACTION_KEY(5001) {

            override fun message(): String {
                TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
            }
        },

        OBJECT_NOT_FOUND(6000) {

            override fun message(): String {
                return "Object not found"
            }
        };

        abstract fun message(): String
    }
}
